# Generated by Django 3.2.12 on 2023-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='websitelink',
            field=models.URLField(null=True),
        ),
    ]
