# Generated by Django 3.2.12 on 2023-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
