# Generated by Django 4.0 on 2023-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_tsubmissions_ttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='notices',
            field=models.ManyToManyField(blank=True, related_name='student_notices', to='base.Notice'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='notices',
            field=models.ManyToManyField(blank=True, related_name='teacher_notices', to='base.Notice'),
        ),
    ]
